# Plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Colorscheme
[[plugins]]
repo = 'jpo/vim-railscasts-theme'
hook_add = '''
  autocmd MyAutoCmd VimEnter * nested colorscheme railscasts
  "" Set background color to red when IME is Japanese
  "if has('multi_byte_ime') || has('xim')
  "  autocmd MyAutoCmd VimEnter * nested highlight CursorIM guibg=Red guifg=NONE
  "endif
'''

# Colorscheme
# [[plugins]]
# repo = 'tomasr/molokai'

# Git wrapper
[[plugins]]
repo =  'tpope/vim-fugitive'
hook_add = '''
  " Status line setup {{{
  " Always show the status line
  set laststatus=2
  " Display file name
  set statusline=%F
  " Display [help] with opening help files
  set statusline+=%h
  " Display [+] if file is modified
  set statusline+=%m
  " show [RO] if file is readonly
  set statusline+=%r
  " Right justify
  set statusline+=%=
  " Display line number / number of lines
  set statusline+=[%l/%L]
  " Display git branch name
  set statusline+=%{fugitive#statusline()}
  " Display type of file
  set statusline+=%y
  " Display file encoding and EOL types
  set statusline+=[%{&fenc}:%{&ff}]
  " }}}
'''

# Surroundings
[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = ['vim-operator-user']
hook_add = '''
  " vim-operator-surround key mappings {{{
  " Set <Space>s as Surround prefix key
  nnoremap [Surround]  <Nop>
  nmap     <Space>s [Surround]
  map <silent> [Surround]a <Plug>(operator-surround-append)
  map <silent> [Surround]d <Plug>(operator-surround-delete)
  map <silent> [Surround]r <Plug>(operator-surround-replace)
  " }}}
'''

# Define youre own operator easily
[[plugins]]
repo = 'kana/vim-operator-user'

# Open URI with browser
[[plugins]]
repo = 'tyru/open-browser.vim'
if = 'has("win32") || has("win64") || has("mac")'
hook_add = '''
  " Open-browser key mappings {{{
  " disable netrw's gx mapping.
  let g:netrw_nogx = 1
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)
  " }}}
'''

# Seemless navigation between tmux panes and vim splits
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
if = 'has("unix") && !has("win32unix")'
#hook_add = '''
#  nnoremap <silent> <BS> :TmuxNavigateLeft<cr>
#'''

# Create your own text objects
[[plugins]]
repo = 'kana/vim-textobj-user'

#####
# Language
#####

## toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

## markdown
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']
hook_add = '''
  let g:vim_markdown_conceal = 0
'''

[[plugins]]
repo = 'kannokanno/previm'
depends = ['open-browser.vim']
if = 'has("win32") || has("win64") || has("mac")'
on_ft = ['markdown']
hook_add = '''
  nnoremap <Space>p :PrevimOpen<cr>
'''

## bash
[[plugins]]
repo = 'vim-scripts/bats.vim'
on_ft = ['sh']

## ruby
[[plugins]]
repo = 'nelstrom/vim-textobj-rubyblock'
on_ft = ['ruby']

## Python
[[plugins]]
# Text object
repo = 'bps/vim-textobj-python'
depends = ['vim-textobj-user']
on_ft = ['python', 'python3']

# Vim's indentation behavior to comply with PEP8
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python', 'python3']

# vim: foldmethod=marker
