# Plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Colorscheme
[[plugins]]
repo = 'jpo/vim-railscasts-theme'
hook_add = '''
  au MyAutoCmd VimEnter * nested colorscheme railscasts
'''

# Colorscheme
# [[plugins]]
# repo = 'tomasr/molokai'

# Git wrapper
[[plugins]]
repo =  'tpope/vim-fugitive'
hook_add = '''
  " Always show the status line
  set laststatus=2
  " Show file name
  set statusline=%F
  " Show [help] with opening help files
  set statusline+=%h
  " Right justify
  set statusline+=%=
  " Show line number / number of lines
  set statusline+=[%l/%L]
  " Show git branch name
  set statusline+=%{fugitive#statusline()}
  " Show type of file
  set statusline+=%y
  " Show file encoding and EOL types
  set statusline+=[%{&fenc}:%{&ff}]
'''

# Completion
[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

#####
# Language
#####

## toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

## markdown
[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']
depends = ['tabular', 'vim-markdown-quote-syntax']
hook_add = '''
  let g:vim_markdown_new_list_item_indent = 2
'''

## bash
[[plugins]]
repo = 'vim-scripts/bats.vim'
on_ft = ['sh']

## ruby
[[plugins]]
repo = 'nelstrom/vim-textobj-rubyblock'
on_ft = ['ruby']
