# Plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Colorscheme
[[plugins]]
repo = 'jpo/vim-railscasts-theme'
hook_add = '''
  au MyAutoCmd VimEnter * nested colorscheme railscasts
'''

# Colorscheme
# [[plugins]]
# repo = 'tomasr/molokai'

# Unite: search and display arbitrary sources
[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_add = '''
  " Set <Space>u as Unite prefix key
  nnoremap [unite]  <Nop>
  nmap     <Space>u [unite]
  " Display buffers when [unite]b is pressed
  nnoremap <silent> [unite]b :<C-u>Unite buffer<CR>
  " Display MRU files when [unite]m is pressed
  nnoremap <silent> [unite]m :<C-u>Unite file_mru<CR>
'''

# Unite MRU sources
[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

# Git wrapper
[[plugins]]
repo =  'tpope/vim-fugitive'
hook_add = '''
  " Status line setup {{{
  " Always show the status line
  set laststatus=2
  " Display file name
  set statusline=%F
  " Display [help] with opening help files
  set statusline+=%h
  " Display [+] if file is modified
  set statusline+=%m
  " show [RO] if file is readonly
  set statusline+=%r
  " Right justify
  set statusline+=%=
  " Display line number / number of lines
  set statusline+=[%l/%L]
  " Display git branch name
  set statusline+=%{fugitive#statusline()}
  " Display type of file
  set statusline+=%y
  " Display file encoding and EOL types
  set statusline+=[%{&fenc}:%{&ff}]
  " }}}
'''

# Completion
[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

#####
# Language
#####

## toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

## markdown
[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']
depends = ['tabular', 'vim-markdown-quote-syntax']
hook_add = '''
  let g:vim_markdown_new_list_item_indent = 2
'''

## bash
[[plugins]]
repo = 'vim-scripts/bats.vim'
on_ft = ['sh']

## ruby
[[plugins]]
repo = 'nelstrom/vim-textobj-rubyblock'
on_ft = ['ruby']

# vim: foldmethod=marker
