" Use the Ricty to font, height is 12pt, width is 6pt, character set Default
set guifont=Ricty:h12:w6:cDEFAULT
" Remove toolbar
set guioptions-=T
" Repair a garbled menu
source $VIMRUNTIME/delmenu.vim
set langmenu=ja_jp.utf-8
source $VIMRUNTIME/menu.vim
" Use twice the width of ASCII characters when display Japanese
set ambiwidth=double
" Remember the last position and the window size
let g:save_window_file = expand('~/.vimwinpos')
augroup SaveWindow
  autocmd!
  autocmd VimLeavePre * call s:save_window()
  function! s:save_window()
    let options = [
      \ 'set columns=' . &columns,
      \ 'set lines=' . &lines,
      \ 'winpos ' . getwinposx() . ' ' . getwinposy(),
      \ ]
    call writefile(options, g:save_window_file)
  endfunction
augroup END

if filereadable(g:save_window_file)
  execute 'source' g:save_window_file
endif
