return {
    "nvim-treesitter/nvim-treesitter",
    opts = {
        ensure_installed = {
            "bash",
            "css",
            "csv",
            "diff",
            "dockerfile",
            "git_config",
            "gitcommit",
            "gitignore",
            "html",
            "javascript",
            "json",
            "just",
            "lua",
            "make",
            "markdown",
            "markdown_inline",
            "mermaid",
            "nu",
            "python",
            "regex",
            "requirements",
            "scss",
            "ssh_config",
            "toml",
            "typescript",
            "vim",
            "vimdoc",
            "xml",
            "yaml",
        },
    },
}
